WIDTH = 3840
HEIGHT = 2160
FPS = 30

WAVE_WIDTH = 1800
WAVE_HEIGHT = 150
WAVE_CENTER_Y = HEIGHT // 2
WAVE_X_START = (WIDTH - WAVE_WIDTH) // 2

SEEK_BAR_H = 6
SEEK_BAR_Y = HEIGHT - 120
SEEK_BAR_X = (WIDTH - WAVE_WIDTH) // 2
SEEK_BAR_W = WAVE_WIDTH

TEXT_X = SEEK_BAR_X
TIME_MARGIN = 20
TEXT_Y_TIME = SEEK_BAR_Y - 40 - TIME_MARGIN
TEXT_Y_ALBUM = TEXT_Y_TIME - 65
TEXT_Y_ARTIST = TEXT_Y_ALBUM - 65
TEXT_Y_TITLE = TEXT_Y_ARTIST - 95

SMOOTHING_WINDOW = 15
TEMPORAL_ALPHA = 0.35

WAVE_FADE_WIDTH = 180

LANG_PREFIXES: dict[str, dict[str, str]] = {
    "en": {"artist": "by ", "album": "from "},
    "pt": {"artist": "por ", "album": "de "},
}

FADE_DURATION = 3.0
FADE_DELAY_WAVE = 0.5
FADE_DELAY_UI = 1.0
