name: Deploy Landing Page

on:
  push:
    branches: ["main"]
    paths:
      - "website/**"
      - ".github/workflows/deploy-website.yml"

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT || 22 }}
          script: |
            cd /root/projects/klangbild
            
            git pull origin main
            
            # Deploy only the website
            docker compose -f website/compose.yml down
            docker compose -f website/compose.yml up -d --build
